# Generated by Django 5.2.4 on 2025-08-21 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenunciaFalsificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_denunciante', models.CharField(max_length=200)),
                ('email_denunciante', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('denuncia_anonima', models.BooleanField(default=False)),
                ('tipo_denuncia', models.CharField(choices=[('falsificacion', 'Certificado Falsificado'), ('alteracion', 'Certificado Alterado'), ('uso_fraudulento', 'Uso Fraudulento'), ('venta_ilegal', 'Venta Ilegal'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('folio_certificado', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_incidente', models.DateField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='denuncias/evidencia/')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En Revisión'), ('validada', 'Validada'), ('enviada_autoridades', 'Enviada a Autoridades'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='recibida', max_length=20)),
                ('fecha_denuncia', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('accion_tomada', models.TextField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(blank=True, null=True)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_procesadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Denuncia de Falsificación',
                'verbose_name_plural': 'Denuncias de Falsificación',
                'ordering': ['-fecha_denuncia'],
            },
        ),
    ]
