#!/usr/bin/env python
import os
import django
from datetime import datetime

# Configurar Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'iccsi.iccsi.settings')
django.setup()

from iccsi.cursos.models import Curso, Organizacion
from iccsi.usuarios.models import Usuario

def importar_cursos_completos():
    print("🚀 Iniciando importación completa de cursos...")
    
    # Buscar el profesor
    try:
        profesor = Usuario.objects.get(username='Eduardo_mednieta_zuñiga')
        print(f"✅ Profesor encontrado: {profesor.get_full_name()}")
    except Usuario.DoesNotExist:
        print("❌ Error: No se encontró el profesor Eduardo_mednieta_zuñiga")
        return
    
    # Crear o buscar organizaciones
    organizaciones = {}
    
    # Fraternidad Migratoria
    fraternidad, created = Organizacion.objects.get_or_create(
        nombre="Fraternidad Migratoria A.C.",
        defaults={
            'descripcion': 'Organización especializada en capacitación y certificaciones profesionales. Registro: Fmi111006-4q2-0013',
            'activo': True
        }
    )
    organizaciones['fraternidad'] = fraternidad
    if created:
        print(f"✅ Organización '{fraternidad.nombre}' creada")
    else:
        print(f"✅ Organización '{fraternidad.nombre}' encontrada")
    
    # Colocación de Proyectos Industriales
    colocacion, created = Organizacion.objects.get_or_create(
        nombre="Colocación de Proyectos Industriales S.C. de R.L. de C.V.",
        defaults={
            'descripcion': 'Organización especializada en proyectos industriales. Registro: CPI-120802-FS1-0013',
            'activo': True
        }
    )
    organizaciones['colocacion'] = colocacion
    if created:
        print(f"✅ Organización '{colocacion.nombre}' creada")
    else:
        print(f"✅ Organización '{colocacion.nombre}' encontrada")
    
    # Lista completa de cursos por organización
    cursos_data = {
        'fraternidad': [
            # Cursos de Fraternidad Migratoria A.C.
            ("ELABORACION DE PROGRAMAS DE PROTECCION CIVIL", 10),
            ("INTEGRACION DE EQUIPOS EN EMERGENCIAS DE SISMOS", 10),
            ("EQUIPOS DE EMERGENCIAS EN EVACUACION EN INCENDIOS", 10),
            ("NORMA OFICIAL MEXICANA NOM-001-STPS-2008, EDIFICIOS, LOCALES, INSTALACIONES Y AREAS EN LOS CENTROS DE TRABAJO CONDICIONES DE SEGURIDAD", 5),
            ("NORMA OFICIAL MEXICANA NOM-002-STPS-2010 CONDICIONES DE SEGURIDAD-PREVENCION Y PROTECCION CONTRA INCENDIOS EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-003-STPS-1999, ACTIVIDADES AGRICOLAS-USO DE INSUMOS FITOSANITARIOS O PLAGUICIDAS E INSUMOS DE NUTRICION VEGETAL O FERTILIZANTES-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-004-STPS-1999 SISTEMAS DE PROTECCION Y DISPOSITIVOS DE SEGURIDAD EN LA MAQUINARIA Y EQUIPO QUE SE UTILICE EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-005-STPS-1998. RELATIVA A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO PARA EL MANEJO, TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
            ("NORMA OFICIAL MEXICANA NOM-006-STPS-2014 MANEJO Y ALMACENAMIENTO DE MATERIALES-CONDICIONES DE SEGURIDAD Y SALUD EN EL TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-007-STPS-2000, ACTIVIDADES AGRÍCOLAS-INSTALACIONES, MAQUINARIA, EQUIPO Y HERRAMIENTAS-CONDICIONES DE SEGURIDAD", 5),
            ("NORMA OFICIAL MEXICANA NOM-008-STPS-2001, ACTIVIDADES DE APROVECHAMIENTO FORESTAL MADERABLE Y DE ASERRADEROS-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-009-STPS-2011, CONDICIONES DE SEGURIDAD PARA REALIZAR TRABAJOS EN ALTURAS", 5),
            ("NORMA OFICIAL MEXICANA NOM-010-STPS-1999, CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO DONDE SE MANEJEN, TRANSPORTEN, PROCESEN O ALMACENEN SUSTANCIAS QUIMICAS CAPACES DE GENERAR CONTAMINACION EN EL MEDIO AMBIENTE LABORAL", 5),
            ("NORMA OFICIAL MEXICANA NOM-011-STPS-2001, CONDICIONES DE SEGURIDAD E HIGIENE PARA EL MANEJO, TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
            ("NORMA OFICIAL MEXICANA NOM-012-STPS-2012, CONDICIONES DE SEGURIDAD Y SALUD EN LOS CENTROS DE TRABAJO DONDE SE MANEJEN FUENTES DE RADIACION IONIZANTE", 5),
            ("NORMA OFICIAL MEXICANA NOM-013-STPS-1993 RELATIVA A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO DONDE SE GENEREN RADIACIONES ELECTROMAGNETICAS NO IONIZANTES", 5),
            ("NORMA OFICIAL MEXICANA NOM-014-STPS-2000 EXPOSICION LABORAL A PRESIONES AMBIENTALES ANORMALES.CONDICIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-015-STPS-2001, CONDICIONES TERMICAS ELEVADAS O ABATIDAS-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-016-STPS-2001, OPERACION Y MANTENIMIENTO DE FERROCARRILES.CONDICIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-017-STPS-2008, EQUIPO DE PROTECCION PERSONAL-SELECCION, USO Y MANEJO EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-018-STPS-2015, SISTEMA ARMONIZADO PARA LA IDENTIFICACION Y COMUNICACION DE PELIGROS Y RIESGOS POR SUSTANCIAS QUIMICAS PELIGROSAS EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-019-STPS-2011, CONSTITUCION, INTEGRACION, ORGANIZACION Y FUNCIONAMIENTO DE LAS COMISIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-020-STPS-2011, RECIPIENTES SUJETOS A PRESION, RECIPIENTES CRIOGENICOS Y GENERADORES DE VAPOR O CALDERAS-FUNCIONAMIENTO-CONDICIONES DE SEGURIDAD", 5),
            ("NORMA OFICIAL MEXICANA NOM-021-STPS-1994, RELATIVA A LOS REQUERIMIENTOS Y CARACTERISTICAS DE LOS INFORMES DE LOS RIESGOS DE TRABAJO QUE OCURRAN, PARA INTEGRAR LAS ESTADISTICAS", 5),
            ("NORMA OFICIAL MEXICANA NOM-022-STPS-2008, ELECTRICIDAD ESTATICA EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 5),
            ("NORMA OFICIAL MEXICANA NOM-023-STPS-2012, MINAS SUBTERRANEAS Y MINAS A CIELO ABIERTO-CONDICIONES DE SEGURIDAD Y SALUD EN EL TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-024-STPS-2001, VIBRACIONES-CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-025-STPS-2008, CONDICIONES DE ILUMINACION EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-026-STPS-2008, COLORES Y SEÑALES DE SEGURIDAD E HIGIENE E IDENTIFICACION DE RIESGOS POR FLUIDOS CONDUCIDOS EN TUBERIAS", 5),
            ("NORMA OFICIAL MEXICANA NOM-027-STPS-2008, ACTIVIDADES DE SOLDADURA Y CORTE-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
            ("NORMA OFICIAL MEXICANA NOM-028-STPS-2012, SISTEMA PARA LA ADMINISTRACION DEL TRABAJO-SEGURIDAD EN LOS PROCESOS Y EQUIPOS CRITICOS QUE MANEJEN SUSTANCIAS QUIMICAS PELIGROSAS", 5),
            ("NORMA OFICIAL MEXICANA NOM-029-STPS-2011, MANTENIMIENTO DE LAS INSTALACIONES ELECTRICAS EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 5),
            ("NORMA OFICIAL MEXICANA NOM-030-STPS-2009, SERVICIOS PREVENTIVOS DE SEGURIDAD Y SALUD EN EL TRABAJO FUNCIONES Y ACTIVIDADES", 5),
            ("NORMA OFICIAL MEXICANA NOM-031-STPS-2011, CONSTRUCCION-CONDICIONES DE SEGURIDAD Y SALUD EN EL TRABAJO", 5),
            ("FUEGO Y SOLDADURA", 5),
            ("PRIMEROS AUXILIOS", 5),
            ("CATA O LOTO", 5),
            ("IZAR O LEVANTAR Y MOVER CARGAS", 5),
            ("SEGURISTA", 5),
            ("NOM-033-STPS-2014. CONDICIONES DE SEGURIDAD PARA REALIZAR TRABAJOS EN ESPACIOS CONFINADOS", 5),
            ("USO RACIONAL DEL EQUIPO DE QUE DISPONE EL PERSONAL DE SEGURIDAD PRIVADA", 5),
            ("INFRAESTRUCTURA DE EMERGENCIA Y CONTROL DE SITUACIONES DE EMERGENCIA", 5),
            ("MANEJO Y USO DE ARMAS Y EQUIPO COMPLEMENTARIO ASI COMO PRACTICAS DE TIRO, EN SU CASO", 5),
            ("AUXILIO A AUTORIDADES E INSTITUCIONES DE SEGURIDAD PUBLICA", 5),
            ("UTILIZACION DE LA FUERZA CORPORAL", 5),
            ("UTILIZACION DE INSTRUMENTOS NO LETALES", 5),
            ("BLOQUEO Y ETIQUETADO", 5),
            ("SUPERVISOR DE SEGURIDAD", 5),
            ("USO CON ELECTRICIDAD", 5),
            ("PREVENCION DE EXPLOSIONES", 5),
            ("MANEJO DE HERRAMIENTAS MANUALES Y DE PODER", 5),
            ("DIPLOMADO EN TECNICO CONSTRUCTOR", 120),
            ("RETROEXCAVADORAS", 5),
            ("TRABAJOS ELECTRICOS DE ALTO RIESGO", 5),
            ("INFRAESTRUCTURA DE EMERGENCIA Y CONTROL DE SITUACIONES DE EMERGENCIA", 5),
            ("MONTACARGAS DE HOMBRE A PIE", 5),
            ("MONTACARGAS", 5),
            ("GRUAS MOVILES", 5),
            ("DISPOSITIVOS DE ELEVACION", 5),
            ("MATERIALES PELIGROSOS", 5),
            ("TRABAJOS CALIENTES", 5),
            ("BLOQUEO CANDADEO ETIQUETADO", 5),
            ("OPERADOR DE MAQUINARIA PESADA", 5),
            ("PLATAFORMAS AEREAS", 5),
            ("SEGURIDAD ELECTRICA", 5),
            ("INTERPRETACION DE LA NORMA ISO 9001 2015", 5),
            ("OPERADOR DE MAQUINA DOBLADORA", 5),
            ("OPERADOR DE RETROEXCAVADORA", 5),
            ("CORTADOR DE FIERRO", 5),
            ("MONTAJE DE ESTUCTURAS METALICAS Y CONCRETO", 5),
            ("RESIDENTE DE OBRA", 5),
            ("OPERADOR DE MOTOCONFORMADORA", 5),
            ("OPERADOR DE TRACTOR", 5),
            ("OPERADOR DE VIBROCOMPACTADOR", 5),
            ("OPERADOR DE EXCAVADORA", 5),
            ("MANTENIMIENTO Y COMBUSTIBLE", 5),
            ("USO Y MANEJO DE EXTINTORES", 5),
            ("TOPOGRAFO", 5),
            ("CADENERO AYUDANTE DE TOPOGRAFO", 5),
            ("MANIOBRISTA", 5),
            ("REFRIGERACION Y AIRE ACONDICIONADO", 5),
            ("SAM & LOTO", 5),
            ("FUEGO", 5),
            ("EQUIPOS DE ELEVACION", 5),
            ("SUBESTACIONES", 5),
            ("ACTIVIDADES DE DEMOLICION", 5),
            ("TALLER DE PRIMEROS AUXILIOS, ENFOCADOS A TRABAJOS DE ALTO RIESGO", 8),
            ("ENTRENAMIENTO EN EL MANEJO DE RIESGO ELECTRICO", 16),
            ("LOTO BLOQUEO DE ENERGIAS PELIGROSAS", 5),
            ("FORMACION DE BRIGADAS", 5),
            ("TRABAJO EN ALTURAS, MANEJO DE ESCALERAS. CUERDAS Y NUDOS", 16),
            ("USO DE HERRAMIENTAS", 5),
            ("ENERGIAS PELIGROSAS", 5),
            ("BLOQUEO Y CANDADEO DE ENERGIA ELECTRICA", 5),
            ("NORMA OFICIAL MEXICANA NOM-016-CRE-2016, ESPECIFICACIONES DE CALIDAD DE LOS PETROLIFEROS", 5),
            ("LOTO", 5),
            ("MATA CHISPA Y TRABAJOS EN CALIENTE CON RIESGO DE INCENDIO", 5),
            ("OPERADOR DE MONTACARGAS", 8),
            ("RESIDUOS PELIGROSOS", 5),
            ("ARMADO DE ANDAMIOS", 5),
            ("FUSION Y PRUEBAS DE FIBRA OPTICA", 5),
            ("TRABAJOS ELECTRICOS EN TABLEROS", 5),
            ("SEGURIDAD Y ETIQUETADO", 5),
            ("AISLAMIENTO DE ENERGIA", 5),
            ("OPERACION SEGURA DE HERRAMIENTAS MANUALES", 5),
            ("TRABAJOS EN ALTURA: CON ANDAMIOS, ESCALERAS, GRUA ARTICULADA, MONTACARGAS", 4),
            ("TRABAJOS CON ENERGIA ELECTRICA", 4),
            ("TRABAJOS CON EQUIPOS QUE GENEREN FUEGO, CHISPA O CALOR", 4),
            ("MAQUINAS Y HERRAMIENTAS", 4),
            ("PROTECCION ANTICAIDAS EN OBRA DE CONSTRUCCION", 5),
            ("RESTREGADORAS, HIDROLAVADORAS DE PISO Y BARREDORAS", 5),
            ("SERVICIO DE LIMPIEZA DE OFICINAS Y ALMACENES", 5),
            ("VENTA, REPARACION, MANTENIMIENTO E INSTALACION DE SUBESTACIONES", 5),
            ("MANTENIMIENTO Y LIMPIEZA", 5),
            ("CARGAS MANUALES", 5),
            ("OPERADOR DE PLATAFORMAS DE ELEVACION, GENIE, TIJERA, ELEVACION, ARTICULADAS", 5),
            ("ESPACIOS CONFINADOS. EXCAVACIONES PROFUNDAS", 5),
            ("CORTE Y SOLDADURA EN TUBERIA DE ACERO", 5),
            ("APLICACION DE PINTURA", 5),
            ("INSTALACION DE AISLAMIENTO TERMICO. INDUSTRIAL. TUBERIAS. AIRE ACONDICIONADO. MUROS", 5),
            ("MANEJO DE CARGAS MANUALES", 5),
            ("MANEJO DE EXTINTORES Y PREVENCION DE INCENDIOS", 5),
            ("BRIGADA DE RESCATE", 5),
            ("BRIGADA CONTRA INCENDIOS", 5),
            ("BRIGADA EN CASO DE SISMOS", 5),
            ("BRIGADA DE PRIMEROS AUXILIOS", 5),
            ("MANEJO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
            ("MEDICION DE SISTEMAS DE TIERRA", 5),
            ("MANEJO DE HERRAMIENTAS Y EQUIPO. CONDICIONES DE TRABAJO DE SEGURIDAD. NOM. 31. IDENTIFICACION DE RIESGOS Y DE PELIGRO", 5),
            ("INTERVENCION DE LINEAS CON FLUIDOS PELIGROSOS", 5),
            ("EXCAVACIONES Y DEMOLICIONES", 5),
            ("SEGURIDAD E HIGIENE EN CONSTRUCCION", 5),
            ("ANALISIS DE ASPECTOS AMBIENTALES", 5),
            ("NORMA OFICIAL MEXICANA NOM-017-STPS-2008 EQUIPO DE PROTECCION PERSONAL-SELECCION, USO Y MANEJO EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-018-STPS-2015 SISTEMA ARMONIZADO PARA LA IDENTIFICACION Y COMUNICACION DE PELIGROS Y RIESGOS POR SUSTANCIAS QUIMICAS PELIGROSAS EN LOS CENTROS DE TRABAJO", 5),
            ("NORMA OFICIAL MEXICANA NOM-022-STPS-2015 ELECTRICIDAD ESTATICA EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 5),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE TOMOGRAFOS", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ACELERADOR LINEAL", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE RESONANCIA MAGNETICA", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE GAMACAMARA", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ESTERILIZADORES", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE EQUIPO DE RX O IMAGENOLOGIA", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE EQUIPO ELECTROMEDICO", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ULTRASONIDOS", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE MONITORES DE SIGNOS VITALES", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE MAQUINAS DE ANESTESIA", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE VAPORIZADORES", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE VENTILADORES VOLUMETRICOS O DE PRESION", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE CUNAS", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE INCUBADORAS", 4),
            ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE EQUIPO DE LABORATORIO", 4),
            ("NOM-035-STPS-2018,FACTORES DE RIESGO PSICOSOCIAL EN EL TRABAJO-IDENTIFICACION,ANALISIS Y PREVENCION", 8),
            ("NOM-008-ASEA-2019,ESTACIONES DE SERVICIO CON FIN ESPECIFICO PARA EL EXPENDIO AL PUBLICO DE GAS LICUADO DE PETROLEO,POR MEDIO DEL LLENADO PARCIAL O TOTAL DE RECIPIENTES PORTATILES", 5),
            ("NOM-006-SESH-2010,TALLERES DE EQUIPOS DE CARBURACION DE GAS LP.-DISEÑO,CONSTRUCCION,OPERACION Y CONDICIONES DE SEGURIDAD", 5),
            ("NOM-005-SESH-2010,EQUIPOS DE CARBURACION DE GAS LP.EN MOTORES DE COMBUSTION INTERNA,INSTALACION Y MANTENIMIENTO", 5),
            ("NOM-004-SEDG-2004,INSTALACIONES DE APROVECHAMIENTO DE GAS LP.DISEÑO Y CONSTRUCCION", 5),
            ("NOM-001-SESH-2014:PLANTAS DE DISTRIBUCION DE GAS LP,DISEÑO,CONSTRUCCION Y CONDICIONES SEGURAS EN SU OPERACION", 5),
            ("NOM-001-CONAGUA-2011,SISTEMAS DE AGUA POTABLE,TOMA DOMICILIARIA ALCANTARILLADO-SANITARIO-HERMETICIDAD ESPECIFICACIONES Y METODOS DE PRUEBA", 4),
            ("NOM-154-SCFI-2005,EQUIPOS CONTRA INCENDIO-EXTINTORES-SERVICIO DE MANTENIMIENTO Y RECARGA", 8),
            ("NOM-053-SCFI-2000,ELEVADORES ELECTRICOS DE TRACCION PARA PASAJEROS Y CARGA ESPECIFICACIONES DE SEGURIDAD Y METODOS DE PRUEBA", 8),
            ("NOM-036-STPS-2018,FACTORES DE RIESGO ERGONOMICO EN EL TRABAJO-IDENTIFICACION-ANALISIS-PREVENCION Y CONTROL,MANEJO MANUAL DE CARGAS", 8),
            ("SUPERVISOR DE SEGURIDAD EN INSTALACIONES ELECTRICAS", 8),
            ("SUPERVISOR DE SEGURIDAD EN MANTENIMIENTO DE EDIFICIOS", 8),
            ("SUPERVISOR DE SEGURIDAD EN CONSTRUCCION", 8),
            ("SUPERVISOR DE SEGURIDAD EN ESPACIOS CONFINADOS", 8),
            ("SUPERVISOR DE SEGURIDAD EN MANTENIMIENTO INDUSTRIAL", 8),
            ("AVANZADO DE EVACUACION", 20),
            ("AVANZADO DE PREVENCION,COMBATE Y EXTINCION DE INCENDIOS", 20),
            ("AVANZADO DE COMUNICACION", 20),
            ("COMITES INTERNOS DE PROTECCION CIVIL", 20),
            ("GRUPO DE APOYO ESPECIAL", 20),
            ("TECNICAS Y MANIOBRAS EN AREA DE RIGGIN ENFOCADO EN AREA DE TELECOMUNICACIONES", 24),
            ("NORMA OFICIAL MEXICANA NOM-002-STPS-2010,CONDICIONES DE SEGURIDAD,PREVENCION Y PROTECCION CONTRA INCENDIOS EN LOS CENTROS DE TRABAJO", 8),
            ("BLOQUEO CANDADEO Y ETIQUETADO (LOTO)", 8),
            ("MANEJO DE HERRAMIENTAS MANUALES Y DE PODER", 8),
            ("NORMA MEXICANA NOM-005-STPS-1998,RELATIVAS A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO PARA EL MANEJO,TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 8),
        ],
        
        'colocacion': [
            # Cursos de Colocación de Proyectos Industriales
            ("NOM-009-STPS-2011, CONDICIONES DE SEGURIDAD PARA REALIZAR TRABAJOS EN ALTURA", 8),
            ("NOM-027-STPS-2008, ACTIVIDADES DE SOLDADURA Y CORTE - CONDICIONES DE SEGURIDAD E HIGIENE", 8),
            ("NOM-029-STPS-2011, MANTENIMIENTO DE LAS INSTALACIONES ELECTRICAS EN LOS CENTROS DE TRABAJO - CONDICIONES DE SEGURIDAD", 8),
            ("MECANICA EN CONSTRUCCION", 5),
            ("ANALISIS DE RIESGOS", 5),
            ("MANEJO DE QUIMICOS", 5),
            ("BLOQUEO Y ETIQUETADO", 5),
            ("MANEJO, MANTENIMIENTO, REPARACION, INSTALACION. VENTA DE PLANTAS DE EMERGENCIA", 5),
            ("PRUEBAS ELECTRICAS A INTERRUPTORES Y UNIDADES DE DISPARO", 5),
            ("OPERADOR DE PLATAFORMAS DE ELEVACION, GENIE, TIJERA, ELEVACION, ARTICULADAS", 8),
            ("TRABAJOS CALIENTES", 8),
            ("EQUIPOS DE EMERGENCIAS EN EVALUACION EN INCENDIOS", 5),
            ("PRIMEROS AUXILIOS", 5),
            ("NOM-005-STPS-1998, RELATIVA A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO PARA EL MANEJO, TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
            ("NOM-002-STPS-2010, CONDICIONES DE SEGURIDAD- PREVENCION Y CONTRA INCENDIOS EN LOS CENTROS DE TRABAJO", 5),
            ("OPERADOR DE FINISHER", 4),
            ("OPERADOR DE COMPACTADORA", 4),
            ("SHOCK ELECTRICO", 4),
            ("SEGURIDAD EN TRABAJOS DE ELECTRICIDAD Y ELECTRONICA", 5),
            ("CONOCIMIENTO ELECTRICO", 4),
            ("TRABAJOS EN ALTURAS", 16),
            ("MANEJO Y USO DE NUDOS Y ESCALERAS", 16),
            ("RAPEL", 5),
            ("ADMINISTRACION DE PROYECTOS", 4),
            ("APLICACION DE IMPERMEABILIZANTE", 4),
            ("BUSQUEDA Y RESCATE", 4),
            ("BRIGADA DE RESPUESTA INMEDIATA", 4),
            ("PLAN DE CONTINGENCIA EN MATERIA DE PROTECCION CIVIL, BRIGADA", 4),
            ("BRIGADA CONTRA INCENDIOS", 4),
            ("ASPECTO E IMPACTO AMBIENTALES", 4),
            ("BASICO DE PROTECCION CIVIL", 4),
            ("BUENAS PRACTICAS DE MANUFACTURA PARA ALIMENTOS", 4),
            ("CUIDADO AMBIENTAL", 4),
            ("CONTROL DE CALIDAD", 4),
            ("NOM-017-STPS-2008, EQUIPO DE PROTECCION PERSONAL-SELECCION, USO Y MANEJO EN LOS CENTROS DE TRABAJO", 8),
            ("PREVENCION Y CUIDADO DEL MEDIO AMBIENTE", 4),
            ("USO Y MANEJO DE HERRAMIENTAS MANUALES", 4),
            ("NOM-033-STPS-2015, CONDICIONES DE SEGURIDAD PARA REALIZAR TRABAJOS EN ESPACIOS CONFINADOS", 8),
            ("MANEJO SEGURO DE CARGAS", 4),
            ("MANEJO DE ENERGIAS PELIGROSAS", 4),
            ("INSTALACION DE CABLEADO ELECTRICO", 4),
            ("SUPERVISOR INDUSTRIAL", 4),
            ("NOM-031-STPS-2011, CONSTRUCCION-CONDICIONES DE SEGURIDAD Y SALUD EN EL TRABAJO", 8),
            ("INSTALACION HIDROSANITARIA, PLOMERIA", 4),
            ("OPERADOR DE TERMOFUSOR", 4),
            ("OPERADOR DE GRUA MOVIL", 4),
            ("OPERADOR DE GRUA ARTICULADA", 4),
            ("OPERADOR DE GRUA CON PLUMA", 4),
            ("SERVICIOS PREVENTIVOS DE SEGURIDAD Y SALUD EN LOS CENTROS DE TRABAJO PREVENTIVO", 4),
            ("COMO ACTUAR EN LAS EMERGENCIAS EN LOS CENTROS DE TRABAJO", 4),
            ("PREVENCION, PROTECCION Y COMBATE DE INCENDIOS", 4),
            ("EVACUACION Y COMUNICACION EN LA CONTINGENCIA", 4),
            ("APLICACION Y COLOCACION DE PINTURAS, PASTAS, TABLAROCA, YESO", 4),
            ("SEGURIDAD EN TRABAJOS EN ALTURA", 4),
            ("PREVENCION DE ACCIDENTES EN EL TRABAJO", 4),
            ("SEGURIDAD EN TRABAJOS ELECTRICOS EN BAJA Y MEDIA TENSION E INDUSTRIAL", 4),
            ("NORMA OFICIAL MEXICANA NOM-019-STPS-2011, CONSTITUCION, INTEGRACION, ORGANIZACION Y FUNCIONAMIENTO DE LAS COMISIONES DE SEGURIDAD E HIGIENE", 8),
            ("CAPACITACION Y BUENAS PRACTICAS DE AMONIACO EN EQUIPOS DE REFRIGERACION", 4),
            ("LEY DE HIDROCARBUROS 17020", 5),
            ("LEY FEDERAL SOBRE METROLOGIA Y NORMALIZACION", 5),
            ("NORMA OFICIAL MEXICANA NOM-005-ASEA-2016. DISEÑO, CONSTRUCCION, OPERACION Y MANTENIMIENTO DE ESTACIONES DE SERVICIO PARA ALMACENAMIENTO Y EXPENDIO DE DIESEL Y GASOLINAS", 5),
            ("NOM-014-CRE-2016, ESPECIFICACIONES DE CALIDAD DE LOS PETROQUIMICOS", 5),
            ("LEY DE LA ASEA", 5),
            ("NORMA OFICIAL MEXICANA NOM-018-STPS-2015, SISTEMA ARMONIZADO PARA LA IDENTIFICACION Y COMUNICACION DE PELIGROS Y RIESGOS POR SUSTANCIAS QUIMICAS PELIGROSAS EN LOS CENTROS DE TRABAJO", 5),
            ("SUPERVISOR DE SEGURIDAD", 10),
            ("NOM-022-STPS-2015, ELECTRICIDAD ESTATICA EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 10),
            ("TRABAJOS EN TRANSFORMADORES", 5),
            ("MANEJO Y TRABAJOS EN COMPRESORES", 5),
            ("MONTAJE DE ESTRUCTURAS METALICAS Y DE CONCRETO", 5),
            ("MECANICA INDUSTRIAL", 5),
            ("NMX-EC-17020-IMNC-2014 REQUISITOS PARA EL FUNCIONAMIENTO DE DIFERENTES TIPOS DE UNIDADES DE VERIFICACION", 5),
            ("TALLER WEDO 2.0 INDUSTRIAL", 40),
            ("TECNICO EN ELECTRICIDAD Y ELECTRONICA", 100),
            ("TECNICO EN AUTOMATIZACION Y CONTROL", 160),
            ("TECNICO EN NEUMATICA, HIDRAULICA Y ELECTRONEUMATICA", 100),
            ("TECNICO EN REDES Y PROTOCOLOS DE COMUNICACION", 120),
            ("TALLER ROBOT CAR DIRIGIDO A LA INDUSTRIA", 60),
            ("TALLER PROGRAMACION CON EV3 LEGO PARA AUTOMATIZACION Y ROBOTICA", 140),
            ("PARA TECNICO EN CELDAS INDUSTRIALES", 120),
            ("PARA TECNICO EN ENERGIAS SUSTENTABLES 1502", 140),
            ("PARA TECNICO EN PROGRAMACION DE ROBOTS INDUSTRIALES", 200),
            ("PARA TECNICO EN SOLDADURA POR RESISTENCIA", 200),
            ("PARA TECNICO EN CONTROLES DE SOLDADURA POR RESISTENCIA", 200),
            ("PARA TECNICO EN MANTENIMIENTO DE EQUIPOS DE SOLDADURA POR RESISTENCIA", 120),
            ("CURSO DE SOLDADURA POR RESISTENCIA", 32),
            ("SUPERVISOR DE SEGURIDAD", 40),
            ("USO Y MANEJO DE MAQUINA COMPACTADORA", 2),
            ("FORMACION DE INSTRUCTORES", 40),
            ("VERIFICADOR INTERNO DE LA NOM-035 STPS 2018", 60),
            ("TRANSPORTES DE CARGA CON CAMION,TORTON,RABON,TRAILER,CAMIONETA,REMOLQUE Y EN GENERAL", 8),
            ("CONTROL DE PLAGAS,FUMIGACION Y SANITIZACION", 8),
            ("MANEJO A LA DEFENSIVA Y PREVENCION DE ACCIDENTES", 8),
            ("GESTION INTEGRAL DE RIESGOS,PROTECCION CIVIL", 60),
            ("GRUA VIAJERA Y MANIOBRAS", 8),
        ]
    }
    
    # Estadísticas generales
    total_cursos_creados = 0
    total_cursos_existentes = 0
    
    # Procesar cada organización
    for org_key, organizacion in organizaciones.items():
        print(f"\n📚 Procesando organización: {organizacion.nombre}")
        print("=" * 60)
        
        cursos_creados = 0
        cursos_existentes = 0
        
        for nombre, horas in cursos_data[org_key]:
            # Verificar si el curso ya existe
            if Curso.objects.filter(nombre=nombre, organizacion=organizacion).exists():
                print(f"⚠️  Curso ya existe: {nombre[:50]}...")
                cursos_existentes += 1
                continue
            
            # Crear el curso
            try:
                curso = Curso.objects.create(
                    nombre=nombre,
                    descripcion=f"Curso de {nombre.lower()} con duración de {horas} horas. Certificación oficial DC-3.",
                    horas=horas,
                    organizacion=organizacion,
                    profesor=profesor,
                    activo=True,
                    fecha_creacion=datetime.now()
                )
                print(f"✅ Curso creado: {nombre[:50]}... ({horas}h)")
                cursos_creados += 1
            except Exception as e:
                print(f"❌ Error al crear curso '{nombre[:50]}...': {e}")
        
        total_cursos_creados += cursos_creados
        total_cursos_existentes += cursos_existentes
        
        print(f"\n📊 Resumen de {organizacion.nombre}:")
        print(f"   • Cursos creados: {cursos_creados}")
        print(f"   • Cursos existentes: {cursos_existentes}")
        print(f"   • Total en esta organización: {cursos_creados + cursos_existentes}")
    
    print(f"\n🎉 ¡IMPORTACIÓN COMPLETADA!")
    print(f"📊 RESUMEN GENERAL:")
    print(f"   • Total cursos creados: {total_cursos_creados}")
    print(f"   • Total cursos existentes: {total_cursos_existentes}")
    print(f"   • Total procesados: {total_cursos_creados + total_cursos_existentes}")
    print(f"   • Profesor: {profesor.get_full_name()}")
    
    # Mostrar estadísticas finales por organización
    for org_key, organizacion in organizaciones.items():
        total_cursos = Curso.objects.filter(organizacion=organizacion).count()
        print(f"   • {organizacion.nombre}: {total_cursos} cursos")

if __name__ == '__main__':
    importar_cursos_completos()
