#!/usr/bin/env python
import os
import django
from datetime import datetime

# Configurar Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'iccsi.iccsi.settings')
django.setup()

from iccsi.cursos.models import Curso, Organizacion
from iccsi.usuarios.models import Usuario

def importar_cursos_fraternidad():
    print("🚀 Iniciando importación de cursos para Fraternidad Migratoria...")
    
    # Buscar o crear la organización
    organizacion, created = Organizacion.objects.get_or_create(
        nombre="Fraternidad Migratoria",
        defaults={
            'descripcion': 'Organización especializada en capacitación y certificaciones profesionales',
            'activo': True
        }
    )
    
    if created:
        print(f"✅ Organización '{organizacion.nombre}' creada")
    else:
        print(f"✅ Organización '{organizacion.nombre}' encontrada")
    
    # Buscar el profesor
    try:
        profesor = Usuario.objects.get(username='Eduardo_mednieta_zuñiga')
        print(f"✅ Profesor encontrado: {profesor.get_full_name()}")
    except Usuario.DoesNotExist:
        print("❌ Error: No se encontró el profesor Eduardo_mednieta_zuñiga")
        return
    
    # Lista completa de cursos de Fraternidad Migratoria
    cursos_data = [
        # Primera imagen - NOMs y cursos básicos
        ("NORMA OFICIAL MEXICANA NOM-002-STPS-2010, CONDICIONES DE SEGURIDAD, PREVENCION Y PROTECCION CONTRA INCENDIOS EN LOS CENTROS DE TRABAJO", 8),
        ("BLOQUEO CANDADEO Y ETIQUETADO (LOTO)", 8),
        ("MANEJO DE HERRAMIENTAS MANUALES Y DE PODER", 8),
        ("NORMA MEXICANA NOM-005-STPS-1998, RELATIVAS A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO PARA EL MANEJO, TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 8),
        
        # Segunda imagen - Cursos de seguridad y mantenimiento
        ("SEGURIDAD E HIGIENE EN CONSTRUCCION", 5),
        ("ANALISIS DE ASPECTOS AMBIENTALES", 5),
        ("NORMA OFICIAL MEXICANA NOM-017-STPS-2008 EQUIPO DE PROTECCION PERSONAL-SELECCION, USO Y MANEJO EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-018-STPS-2015 SISTEMA ARMONIZADO PARA LA IDENTIFICACION Y COMUNICACION DE PELIGROS Y RIESGOS POR SUSTANCIAS QUIMICAS PELIGROSAS EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-022-STPS-2015 ELECTRICIDAD ESTATICA EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 5),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE TOMOGRAFOS", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ACELERADOR LINEAL", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE RESONANCIA MAGNETICA", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE GAMACAMARA", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ESTERILIZADORES", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE EQUIPO DE RX O IMAGENOLOGIA", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE EQUIPO ELECTROMEDICO", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ULTRASONIDOS", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE MONITORES DE SIGNOS VITALES", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE MAQUINAS DE ANESTESIA", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE VAPORIZADORES", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE VENTILADORES VOLUMETRICOS O DE PRESION", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE CUNAS", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE INCUBADORAS", 4),
        ("SERVICIOS DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE EQUIPO DE LABORATORIO", 4),
        
        # Tercera imagen - Cursos avanzados y NOMs
        ("NOM-035-STPS-2018, FACTORES DE RIESGO PSICOSOCIAL EN EL TRABAJO-IDENTIFICACION, ANALISIS Y PREVENCION", 8),
        ("NOM-008-ASEA-2019, ESTACIONES DE SERVICIO CON FIN ESPECIFICO PARA EL EXPENDIO AL PUBLICO DE GAS LICUADO DE PETROLEO, POR MEDIO DEL LLENADO PARCIAL O TOTAL DE RECIPIENTES PORTATILES", 5),
        ("NOM-006-SESH-2010, TALLERES DE EQUIPOS DE CARBURACION DE GAS LP.-DISEÑO, CONSTRUCCION, OPERACION Y CONDICIONES DE SEGURIDAD", 5),
        ("NOM-005-SESH-2010, EQUIPOS DE CARBURACION DE GAS LP.EN MOTORES DE COMBUSTION INTERNA, INSTALACION Y MANTENIMIENTO", 5),
        ("NOM-004-SEDG-2004, INSTALACIONES DE APROVECHAMIENTO DE GAS LP.DISEÑO Y CONSTRUCCION", 5),
        ("NOM-001-SESH-2014:PLANTAS DE DISTRIBUCION DE GAS LP, DISEÑO, CONSTRUCCION Y CONDICIONES SEGURAS EN SU OPERACION", 5),
        ("NOM-001-CONAGUA-2011, SISTEMAS DE AGUA POTABLE, TOMA DOMICILIARIA ALCANTARILLADO-SANITARIO-HERMETICIDAD ESPECIFICACIONES Y METODOS DE PRUEBA", 4),
        ("NOM-154-SCFI-2005, EQUIPOS CONTRA INCENDIO-EXTINTORES-SERVICIO DE MANTENIMIENTO Y RECARGA", 8),
        ("NOM-053-SCFI-2000, ELEVADORES ELECTRICOS DE TRACCION PARA PASAJEROS Y CARGA ESPECIFICACIONES DE SEGURIDAD Y METODOS DE PRUEBA", 8),
        ("NOM-036-STPS-2018,FACTORES DE RIESGO ERGONOMICO EN EL TRABAJO-IDENTIFICACION-ANALISIS-PREVENCION Y CONTROL, MANEJO MANUAL DE CARGAS", 8),
        ("SUPERVISOR DE SEGURIDAD EN INSTALACIONES ELECTRICAS", 8),
        ("SUPERVISOR DE SEGURIDAD EN MANTENIMIENTO DE EDIFICIOS", 8),
        ("SUPERVISOR DE SEGURIDAD EN CONSTRUCCION", 8),
        ("SUPERVISOR DE SEGURIDAD EN ESPACIOS CONFINADOS", 8),
        ("SUPERVISOR DE SEGURIDAD EN MANTENIMIENTO INDUSTRIAL", 8),
        ("AVANZADO DE EVACUACION", 20),
        ("AVANZADO DE PREVENCION, COMBATE Y EXTINCION DE INCENDIOS", 20),
        ("AVANZADO DE COMUNICACION", 20),
        ("COMITES INTERNOS DE PROTECCION CIVIL", 20),
        ("GRUPO DE APOYO ESPECIAL", 20),
        ("TECNICAS Y MANIOBRAS EN AREA DE RIGGIN ENFOCADO EN AREA DE TELECOMUNICACIONES", 24),
        
        # Cuarta imagen - Cursos de operación y seguridad
        ("MONTACARGAS DE HOMBRE A PIE", 5),
        ("MONTACARGAS", 5),
        ("GRUAS MOVILES", 5),
        ("DISPOSITIVOS DE ELEVACION", 5),
        ("MATERIALES PELIGROSOS", 5),
        ("TRABAJOS CALIENTES", 5),
        ("BLOQUEO CANDADEO ETIQUETADO", 5),
        ("OPERADOR DE MAQUINARIA PESADA", 5),
        ("PLATAFORMAS AEREAS", 5),
        ("SEGURIDAD ELECTRICA", 5),
        ("INTERPRETACION DE LA NORMA ISO 9001 2015", 5),
        ("OPERADOR DE MAQUINA DOBLADORA", 5),
        ("OPERADOR DE RETROEXCAVADORA", 5),
        ("CORTADOR DE FIERRO", 5),
        ("MONTAJE DE ESTUCTURAS METALICAS Y CONCRETO", 5),
        ("RESIDENTE DE OBRA", 5),
        ("OPERADOR DE MOTOCONFORMADORA", 5),
        ("OPERADOR DE TRACTOR", 5),
        ("OPERADOR DE VIBROCOMPACTADOR", 5),
        ("OPERADOR DE EXCAVADORA", 5),
        ("MANTENIMIENTO Y COMBUSTIBLE", 5),
        ("USO Y MANEJO DE EXTINTORES", 5),
        ("TOPOGRAFO", 5),
        ("CADENERO AYUDANTE DE TOPOGRAFO", 5),
        ("MANIOBRISTA", 5),
        ("REFRIGERACION Y AIRE ACONDICIONADO", 5),
        ("SAM & LOTO", 5),
        ("FUEGO", 5),
        ("EQUIPOS DE ELEVACION", 5),
        ("SUBESTACIONES", 5),
        ("ACTIVIDADES DE DEMOLICION", 5),
        ("TALLER DE PRIMEROS AUXILIOS, ENFOCADOS A TRABAJOS DE ALTO RIESGO", 8),
        ("ENTRENAMIENTO EN EL MANEJO DE RIESGO ELECTRICO", 16),
        ("LOTO BLOQUEO DE ENERGIAS PELIGROSAS", 5),
        ("FORMACION DE BRIGADAS", 5),
        ("TRABAJO EN ALTURAS, MANEJO DE ESCALERAS. CUERDAS Y NUDOS", 16),
        ("USO DE HERRAMIENTAS", 5),
        ("ENERGIAS PELIGROSAS", 5),
        ("BLOQUEO Y CANDADEO DE ENERGIA ELECTRICA", 5),
        ("NORMA OFICIAL MEXICANA NOM-016-CRE-2016, ESPECIFICACIONES DE CALIDAD DE LOS PETROLIFEROS", 5),
        ("LOTO", 5),
        
        # Quinta imagen - NOMs adicionales
        ("NORMA OFICIAL MEXICANA NOM-012-STPS-2012, CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO DONDE SE GENERE RUIDO", 5),
        ("NORMA OFICIAL MEXICANA NOM-013-STPS-1993, RELATIVA A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO DONDE SE GENERE RADIACION IONIZANTE", 5),
        ("NORMA OFICIAL MEXICANA NOM-014-STPS-2000, EXPOSICION A RADIACIONES ELECTROMAGNETICAS NO IONIZANTES-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-015-STPS-2001, CONDICIONES TERMICAS ELEVADAS O ABATIDAS-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-016-STPS-2001, OPERACION Y MANTENIMIENTO DE FERROCARRILES-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-017-STPS-2008, EQUIPO DE PROTECCION PERSONAL-SELECCION, USO Y MANEJO EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-018-STPS-2015, SISTEMA ARMONIZADO PARA LA IDENTIFICACION Y COMUNICACION DE PELIGROS Y RIESGOS POR SUSTANCIAS QUIMICAS PELIGROSAS EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-019-STPS-2011, CONSTITUCION, INTEGRACION, ORGANIZACION Y FUNCIONAMIENTO DE LAS COMISIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-020-STPS-2011, RECIPIENTES SUJETOS A PRESION Y CALDERAS-FUNCIONES Y ACTIVIDADES", 5),
        ("NORMA OFICIAL MEXICANA NOM-021-STPS-1993, INFORMES DE LOS RIESGOS DE TRABAJO-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-022-STPS-2015, ELECTRICIDAD ESTATICA EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 5),
        ("NORMA OFICIAL MEXICANA NOM-023-STPS-2012, MINAS SUBTERRANEAS Y MINAS A CIELO ABIERTO-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-024-STPS-2001, VIBRACIONES-CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-025-STPS-2008, ILUMINACION EN LOS CENTROS DE TRABAJO", 5),
        
        # Sexta imagen - Cursos adicionales
        ("NORMA OFICIAL MEXICANA NOM-026-STPS-2008, COLORES Y SEÑALES DE SEGURIDAD E HIGIENE E IDENTIFICACION DE RIESGOS POR FLUIDOS CONDUCIDOS EN TUBERIAS", 5),
        ("NORMA OFICIAL MEXICANA NOM-027-STPS-2008, ACTIVIDADES DE SOLDADURA Y CORTE-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-028-STPS-2012, SISTEMA PARA LA ADMINISTRACION DEL TRABAJO-SEGURIDAD EN LOS PROCESOS Y EQUIPOS CRITICOS QUE MANEJEN SUSTANCIAS QUIMICAS PELIGROSAS", 5),
        ("NORMA OFICIAL MEXICANA NOM-029-STPS-2011, MANTENIMIENTO DE LAS INSTALACIONES ELECTRICAS EN LOS CENTROS DE TRABAJO-CONDICIONES DE SEGURIDAD", 5),
        ("NORMA OFICIAL MEXICANA NOM-030-STPS-2009, SERVICIOS PREVENTIVOS DE SEGURIDAD Y SALUD EN EL TRABAJO FUNCIONES Y ACTIVIDADES", 5),
        ("NORMA OFICIAL MEXICANA NOM-031-STPS-2011, CONSTRUCCION-CONDICIONES DE SEGURIDAD Y SALUD EN EL TRABAJO", 5),
        ("FUEGO Y SOLDADURA", 5),
        ("PRIMEROS AUXILIOS", 5),
        ("CATA O LOTO", 5),
        ("IZAR O LEVANTAR Y MOVER CARGAS", 5),
        ("SEGURISTA", 5),
        ("NOM-033-STPS-2014. CONDICIONES DE SEGURIDAD PARA REALIZAR TRABAJOS EN ESPACIOS CONFINADOS", 5),
        ("USO RACIONAL DEL EQUIPO DE QUE DISPONE EL PERSONAL DE SEGURIDAD PRIVADA", 5),
        ("INFRAESTRUCTURA DE EMERGENCIA Y CONTROL DE SITUACIONES DE EMERGENCIA", 5),
        ("MANEJO Y USO DE ARMAS Y EQUIPO COMPLEMENTARIO ASI COMO PRACTICAS DE TIRO, EN SU CASO", 5),
        ("AUXILIO A AUTORIDADES E INSTITUCIONES DE SEGURIDAD PUBLICA", 5),
        ("UTILIZACION DE LA FUERZA CORPORAL", 5),
        ("UTILIZACION DE INSTRUMENTOS NO LETALES", 5),
        ("BLOQUEO Y ETIQUETADO", 5),
        ("SUPERVISOR DE SEGURIDAD", 5),
        ("USO CON ELECTRICIDAD", 5),
        ("PREVENCION DE EXPLOSIONES", 5),
        ("MANEJO DE HERRAMIENTAS MANUALES Y DE PODER", 5),
        ("DIPLOMADO EN TECNICO CONSTRUCTOR", 120),
        ("RETROEXCAVADORAS", 5),
        ("TRABAJOS ELECTRICOS DE ALTO RIESGO", 5),
        ("INFRAESTRUCTURA DE EMERGENCIA Y CONTROL DE SITUACIONES DE EMERGENCIA", 5),
        
        # Séptima imagen - Cursos de Fraternidad Migratoria A.C.
        ("ELABORACION DE PROGRAMAS DE PROTECCION CIVIL", 10),
        ("INTEGRACION DE EQUIPOS EN EMERGENCIAS DE SISMOS", 10),
        ("EQUIPOS DE EMERGENCIAS EN EVACUACION EN INCENDIOS", 10),
        ("NORMA OFICIAL MEXICANA NOM-001-STPS-2008, EDIFICIOS, LOCALES, INSTALACIONES Y AREAS EN LOS CENTROS DE TRABAJO CONDICIONES DE SEGURIDAD", 5),
        ("NORMA OFICIAL MEXICANA NOM-002-STPS-2010 CONDICIONES DE SEGURIDAD-PREVENCION Y PROTECCION CONTRA INCENDIOS EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-003-STPS-1999, ACTIVIDADES AGRICOLAS-USO DE INSUMOS FITOSANITARIOS O PLAGUICIDAS E INSUMOS DE NUTRICION VEGETAL O FERTILIZANTES-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-004-STPS-1999 SISTEMAS DE PROTECCION Y DISPOSITIVOS DE SEGURIDAD EN LA MAQUINARIA Y EQUIPO QUE SE UTILICE EN LOS CENTROS DE TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-005-STPS-1998. RELATIVA A LAS CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO PARA EL MANEJO, TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
        ("NORMA OFICIAL MEXICANA NOM-006-STPS-2014 MANEJO Y ALMACENAMIENTO DE MATERIALES-CONDICIONES DE SEGURIDAD Y SALUD EN EL TRABAJO", 5),
        ("NORMA OFICIAL MEXICANA NOM-007-STPS-2000, ACTIVIDADES AGRÍCOLAS-INSTALACIONES, MAQUINARIA, EQUIPO Y HERRAMIENTAS-CONDICIONES DE SEGURIDAD", 5),
        ("NORMA OFICIAL MEXICANA NOM-008-STPS-2001, ACTIVIDADES DE APROVECHAMIENTO FORESTAL MADERABLE Y DE ASERRADEROS-CONDICIONES DE SEGURIDAD E HIGIENE", 5),
        ("NORMA OFICIAL MEXICANA NOM-009-STPS-2011, CONDICIONES DE SEGURIDAD PARA REALIZAR TRABAJOS EN ALTURAS", 5),
        ("NORMA OFICIAL MEXICANA NOM-010-STPS-1999, CONDICIONES DE SEGURIDAD E HIGIENE EN LOS CENTROS DE TRABAJO DONDE SE MANEJEN, TRANSPORTEN, PROCESEN O ALMACENEN SUSTANCIAS QUIMICAS CAPACES DE GENERAR CONTAMINACION EN EL MEDIO AMBIENTE LABORAL", 5),
        ("NORMA OFICIAL MEXICANA NOM-011-STPS-2001, CONDICIONES DE SEGURIDAD E HIGIENE PARA EL MANEJO, TRANSPORTE Y ALMACENAMIENTO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
        
        # Octava imagen - Cursos adicionales
        ("MATA CHISPA Y TRABAJOS EN CALIENTE CON RIESGO DE INCENDIO", 5),
        ("OPERADOR DE MONTACARGAS", 8),
        ("RESIDUOS PELIGROSOS", 5),
        ("ARMADO DE ANDAMIOS", 5),
        ("FUSION Y PRUEBAS DE FIBRA OPTICA", 5),
        ("TRABAJOS ELECTRICOS EN TABLEROS", 5),
        ("SEGURIDAD Y ETIQUETADO", 5),
        ("AISLAMIENTO DE ENERGIA", 5),
        ("OPERACION SEGURA DE HERRAMIENTAS MANUALES", 5),
        ("TRABAJOS EN ALTURA: CON ANDAMIOS, ESCALERAS, GRUA ARTICULADA, MONTACARGAS", 4),
        ("TRABAJOS CON ENERGIA ELECTRICA", 4),
        ("TRABAJOS CON EQUIPOS QUE GENEREN FUEGO, CHISPA O CALOR", 4),
        ("MAQUINAS Y HERRAMIENTAS", 4),
        ("PROTECCION ANTICAIDAS EN OBRA DE CONSTRUCCION", 5),
        ("RESTREGADORAS, HIDROLAVADORAS DE PISO Y BARREDORAS", 5),
        ("SERVICIO DE LIMPIEZA DE OFICINAS Y ALMACENES", 5),
        ("VENTA, REPARACION, MANTENIMIENTO E INSTALACION DE SUBESTACIONES", 5),
        ("MANTENIMIENTO Y LIMPIEZA", 5),
        ("CARGAS MANUALES", 5),
        ("OPERADOR DE PLATAFORMAS DE ELEVACION, GENIE, TIJERA, ELEVACION, ARTICULADAS", 5),
        ("ESPACIOS CONFINADOS. EXCAVACIONES PROFUNDAS", 5),
        ("CORTE Y SOLDADURA EN TUBERIA DE ACERO", 5),
        ("APLICACION DE PINTURA", 5),
        ("INSTALACION DE AISLAMIENTO TERMICO. INDUSTRIAL. TUBERIAS. AIRE ACONDICIONADO. MUROS", 5),
        ("MANEJO DE CARGAS MANUALES", 5),
        ("MANEJO DE EXTINTORES Y PREVENCION DE INCENDIOS", 5),
        ("BRIGADA DE RESCATE", 5),
        ("BRIGADA CONTRA INCENDIOS", 5),
        ("BRIGADA EN CASO DE SISMOS", 5),
        ("BRIGADA DE PRIMEROS AUXILIOS", 5),
        ("MANEJO DE SUSTANCIAS QUIMICAS PELIGROSAS", 5),
        ("MEDICION DE SISTEMAS DE TIERRA", 5),
        ("MANEJO DE HERRAMIENTAS Y EQUIPO. CONDICIONES DE TRABAJO DE SEGURIDAD. NOM. 31. IDENTIFICACION DE RIESGOS Y DE PELIGRO", 5),
        ("INTERVENCION DE LINEAS CON FLUIDOS PELIGROSOS", 5),
        ("EXCAVACIONES Y DEMOLICIONES", 5),
    ]
    
    # Crear los cursos
    cursos_creados = 0
    cursos_existentes = 0
    
    for nombre, horas in cursos_data:
        # Verificar si el curso ya existe
        if Curso.objects.filter(nombre=nombre, organizacion=organizacion).exists():
            print(f"⚠️  Curso ya existe: {nombre[:50]}...")
            cursos_existentes += 1
            continue
        
        # Crear el curso
        try:
            curso = Curso.objects.create(
                nombre=nombre,
                descripcion=f"Curso de {nombre.lower()} con duración de {horas} horas. Certificación oficial DC-3.",
                horas=horas,
                organizacion=organizacion,
                profesor=profesor,
                activo=True,
                fecha_creacion=datetime.now()
            )
            print(f"✅ Curso creado: {nombre[:50]}... ({horas}h)")
            cursos_creados += 1
        except Exception as e:
            print(f"❌ Error al crear curso '{nombre[:50]}...': {e}")
    
    print(f"\n🎉 ¡IMPORTACIÓN COMPLETADA!")
    print(f"📊 Resumen:")
    print(f"   • Cursos creados: {cursos_creados}")
    print(f"   • Cursos existentes: {cursos_existentes}")
    print(f"   • Total procesados: {len(cursos_data)}")
    print(f"   • Organización: {organizacion.nombre}")
    print(f"   • Profesor: {profesor.get_full_name()}")
    
    # Mostrar estadísticas finales
    total_cursos = Curso.objects.filter(organizacion=organizacion).count()
    print(f"   • Total de cursos en la organización: {total_cursos}")

if __name__ == '__main__':
    importar_cursos_fraternidad()
