[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn iccsi.iccsi.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11.0"
DJANGO_SETTINGS_MODULE = "iccsi.iccsi.settings"
