# Generated by Django 5.2.4 on 2025-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_horas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificadodc3',
            name='horas_curso',
            field=models.PositiveSmallIntegerField(choices=[(4, '4 horas'), (5, '5 horas'), (8, '8 horas'), (10, '10 horas'), (12, '12 horas'), (16, '16 horas')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
