# Generated by Django 5.2.4 on 2025-08-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_duracion_horas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'organizacion')},
        ),
    ]
