# Generated by Django 5.2.4 on 2025-08-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoDC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('imagen', models.ImageField(upload_to='plantillas/logos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.empresa')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.organizacion')),
            ],
            options={
                'verbose_name': 'Logo DC-3',
                'verbose_name_plural': 'Logos DC-3',
            },
        ),
        migrations.CreateModel(
            name='PlantillaDC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('archivo', models.FileField(upload_to='plantillas/dc3/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.empresa')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.organizacion')),
            ],
            options={
                'verbose_name': 'Plantilla DC-3',
                'verbose_name_plural': 'Plantillas DC-3',
            },
        ),
    ]
