# Generated by Django 5.2.4 on 2025-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_logodc3_plantilladc3'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadodc3',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificadodc3',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificadodc3',
            name='nombres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificadodc3',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
