# Generated by Django 5.2.4 on 2025-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_certificadodc3_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadodc3',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/dc3/'),
        ),
    ]
