# Generated by Django 5.2.4 on 2025-08-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_certificadodc3_archivo_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCertificadoDC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo_alumno', models.CharField(max_length=300)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=18)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rfc_empresa', models.CharField(max_length=13)),
                ('nombre_curso', models.CharField(max_length=255)),
                ('horas_curso', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('instructor_nombre', models.CharField(max_length=200)),
                ('codigo_verificacion', models.CharField(max_length=12, unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_certificados', to='cursos.inscripcion')),
            ],
            options={
                'verbose_name': 'Historial Certificado DC-3',
                'verbose_name_plural': 'Historial Certificados DC-3',
                'indexes': [models.Index(fields=['codigo_verificacion'], name='cursos_hist_codigo__3e4b3d_idx'), models.Index(fields=['nombre_completo_alumno', 'nombre_empresa'], name='cursos_hist_nombre__50b1e9_idx'), models.Index(fields=['curp'], name='cursos_hist_curp_10bc92_idx')],
            },
        ),
    ]
