# Generated by Django 5.2.4 on 2025-08-19 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_historialcertificadodc3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcertificadodc3',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='historialcertificadodc3',
            index=models.Index(fields=['folio'], name='cursos_hist_folio_cac550_idx'),
        ),
    ]
