# Generated by Django 5.2.4 on 2025-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_historialcertificadodc3_folio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodc3',
            name='horas_curso',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
