# Generated by Django 5.2.4 on 2025-08-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_factura_detallefactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc_emisor', models.CharField(max_length=13, verbose_name='RFC del Emisor')),
                ('nombre_emisor', models.CharField(max_length=300, verbose_name='Nombre/Razón Social')),
                ('regimen_fiscal', models.CharField(max_length=10, verbose_name='Régimen Fiscal')),
                ('direccion_fiscal', models.TextField(verbose_name='Dirección Fiscal')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(default='MEX', max_length=3, verbose_name='País')),
                ('pac_nombre', models.CharField(max_length=100, verbose_name='Nombre del PAC')),
                ('pac_url', models.URLField(verbose_name='URL del PAC')),
                ('pac_usuario', models.CharField(max_length=100, verbose_name='Usuario PAC')),
                ('pac_password', models.CharField(max_length=100, verbose_name='Contraseña PAC')),
                ('certificado_archivo', models.FileField(upload_to='certificados/', verbose_name='Certificado Digital (.cer)')),
                ('llave_privada_archivo', models.FileField(upload_to='certificados/', verbose_name='Llave Privada (.key)')),
                ('llave_privada_password', models.CharField(max_length=100, verbose_name='Contraseña Llave Privada')),
                ('serie_factura', models.CharField(default='A', max_length=10, verbose_name='Serie de Factura')),
                ('folio_inicial', models.IntegerField(default=1, verbose_name='Folio Inicial')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración Activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Fiscal',
                'verbose_name_plural': 'Configuraciones Fiscales',
            },
        ),
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='UUID')),
                ('folio_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio Fiscal')),
                ('serie', models.CharField(max_length=10, verbose_name='Serie')),
                ('folio', models.CharField(max_length=20, verbose_name='Folio')),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('T', 'Traslado'), ('N', 'Nómina'), ('P', 'Pago')], default='I', max_length=1, verbose_name='Tipo de Comprobante')),
                ('forma_pago', models.CharField(default='01', max_length=10, verbose_name='Forma de Pago')),
                ('metodo_pago', models.CharField(default='PUE', max_length=10, verbose_name='Método de Pago')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Tipo de Cambio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Timbrado')),
                ('sello_cfd', models.TextField(blank=True, null=True, verbose_name='Sello CFD')),
                ('sello_sat', models.TextField(blank=True, null=True, verbose_name='Sello SAT')),
                ('cadena_original', models.TextField(blank=True, null=True, verbose_name='Cadena Original')),
                ('xml_original', models.FileField(blank=True, null=True, upload_to='cfdi/xml/', verbose_name='XML Original')),
                ('xml_timbrado', models.FileField(blank=True, null=True, upload_to='cfdi/xml/', verbose_name='XML Timbrado')),
                ('pdf_timbrado', models.FileField(blank=True, null=True, upload_to='cfdi/pdf/', verbose_name='PDF Timbrado')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('timbrado', 'Timbrado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='borrador', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cfdi', to='cursos.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'CFDI',
                'verbose_name_plural': 'CFDIs',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_producto_servicio', models.CharField(max_length=20, verbose_name='Clave Producto/Servicio SAT')),
                ('clave_unidad', models.CharField(max_length=10, verbose_name='Clave Unidad SAT')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('unidad', models.CharField(max_length=20, verbose_name='Unidad')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Valor Unitario')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('iva_trasladado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA Trasladado')),
                ('iva_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA Retenido')),
                ('cfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='cursos.cfdi', verbose_name='CFDI')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Concepto CFDI',
                'verbose_name_plural': 'Conceptos CFDI',
            },
        ),
        migrations.CreateModel(
            name='ImpuestoCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('traslados', 'Traslados'), ('retenciones', 'Retenciones')], max_length=20, verbose_name='Tipo de Impuesto')),
                ('impuesto', models.CharField(max_length=10, verbose_name='Impuesto')),
                ('tipo_factor', models.CharField(max_length=10, verbose_name='Tipo Factor')),
                ('tasa_cuota', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Tasa o Cuota')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('cfdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='cursos.cfdi', verbose_name='CFDI')),
            ],
            options={
                'verbose_name': 'Impuesto CFDI',
                'verbose_name_plural': 'Impuestos CFDI',
            },
        ),
        migrations.CreateModel(
            name='ReceptorCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre/Razón Social')),
                ('regimen_fiscal', models.CharField(max_length=10, verbose_name='Régimen Fiscal')),
                ('direccion_fiscal', models.TextField(verbose_name='Dirección Fiscal')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(default='MEX', max_length=3, verbose_name='País')),
                ('uso_cfdi', models.CharField(default='G01', max_length=10, verbose_name='Uso del CFDI')),
                ('cfdi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='cursos.cfdi', verbose_name='CFDI')),
            ],
            options={
                'verbose_name': 'Receptor CFDI',
                'verbose_name_plural': 'Receptores CFDI',
            },
        ),
    ]
