# Generated by Django 5.2.4 on 2025-08-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_configuracionfiscal_cfdi_conceptocfdi_impuestocfdi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfdi',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='conceptocfdi',
            name='cfdi',
        ),
        migrations.RemoveField(
            model_name='receptorcfdi',
            name='cfdi',
        ),
        migrations.RemoveField(
            model_name='impuestocfdi',
            name='cfdi',
        ),
        migrations.RemoveField(
            model_name='conceptocfdi',
            name='curso',
        ),
        migrations.DeleteModel(
            name='ConfiguracionFiscal',
        ),
        migrations.DeleteModel(
            name='ReceptorCFDI',
        ),
        migrations.DeleteModel(
            name='CFDI',
        ),
        migrations.DeleteModel(
            name='ImpuestoCFDI',
        ),
        migrations.DeleteModel(
            name='ConceptoCFDI',
        ),
    ]
