# Generated by Django 5.2.4 on 2025-08-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_remove_cfdi_factura_remove_conceptocfdi_cfdi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='empresa_cliente',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
