# Generated by Django 5.2.4 on 2025-08-28 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_remove_factura_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=380.0, max_digits=10, verbose_name='Precio')),
                ('moneda', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Costo de Curso',
                'verbose_name_plural': 'Costos de Cursos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=380.0, max_digits=10, verbose_name='Monto')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('paypal', 'PayPal'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('oxxo', 'OXXO')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='cursos.inscripcion', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado'],
            },
        ),
    ]
