# Generated by Django 5.2.4 on 2025-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_costocurso_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Charge ID'),
        ),
        migrations.AddField(
            model_name='pago',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Client Secret'),
        ),
        migrations.AddField(
            model_name='pago',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='pago',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe Status'),
        ),
    ]
